/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedNewRouteImport } from './routes/_protected/new'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard.index'
import { Route as ProtectedDashboardAlertsRouteImport } from './routes/_protected/dashboard.alerts'
import { Route as ProtectedDashboardInboundsRouteImport } from './routes/_protected/dashboard.inbounds'
import { Route as ProtectedDashboardMentionsRouteImport } from './routes/_protected/dashboard.mentions'
import { Route as ProtectedDashboardOutboundRouteImport } from './routes/_protected/dashboard.outbound'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected/dashboard.settings'
import { Route as ProtectedDashboardSubredditsRouteImport } from './routes/_protected/dashboard.subreddits'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNewRoute = ProtectedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardAlertsRoute =
  ProtectedDashboardAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardInboundsRoute =
  ProtectedDashboardInboundsRouteImport.update({
    id: '/inbounds',
    path: '/inbounds',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMentionsRoute =
  ProtectedDashboardMentionsRouteImport.update({
    id: '/mentions',
    path: '/mentions',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardOutboundRoute =
  ProtectedDashboardOutboundRouteImport.update({
    id: '/outbound',
    path: '/outbound',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSubredditsRoute =
  ProtectedDashboardSubredditsRouteImport.update({
    id: '/subreddits',
    path: '/subreddits',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/new': typeof ProtectedNewRoute
  '/settings': typeof ProtectedSettingsRoute
  '/dashboard/alerts': typeof ProtectedDashboardAlertsRoute
  '/dashboard/inbounds': typeof ProtectedDashboardInboundsRoute
  '/dashboard/mentions': typeof ProtectedDashboardMentionsRoute
  '/dashboard/outbound': typeof ProtectedDashboardOutboundRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/subreddits': typeof ProtectedDashboardSubredditsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/new': typeof ProtectedNewRoute
  '/settings': typeof ProtectedSettingsRoute
  '/dashboard/alerts': typeof ProtectedDashboardAlertsRoute
  '/dashboard/inbounds': typeof ProtectedDashboardInboundsRoute
  '/dashboard/mentions': typeof ProtectedDashboardMentionsRoute
  '/dashboard/outbound': typeof ProtectedDashboardOutboundRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/subreddits': typeof ProtectedDashboardSubredditsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/new': typeof ProtectedNewRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/dashboard/alerts': typeof ProtectedDashboardAlertsRoute
  '/_protected/dashboard/inbounds': typeof ProtectedDashboardInboundsRoute
  '/_protected/dashboard/mentions': typeof ProtectedDashboardMentionsRoute
  '/_protected/dashboard/outbound': typeof ProtectedDashboardOutboundRoute
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/_protected/dashboard/subreddits': typeof ProtectedDashboardSubredditsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/dashboard'
    | '/new'
    | '/settings'
    | '/dashboard/alerts'
    | '/dashboard/inbounds'
    | '/dashboard/mentions'
    | '/dashboard/outbound'
    | '/dashboard/settings'
    | '/dashboard/subreddits'
    | '/api/auth/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/new'
    | '/settings'
    | '/dashboard/alerts'
    | '/dashboard/inbounds'
    | '/dashboard/mentions'
    | '/dashboard/outbound'
    | '/dashboard/settings'
    | '/dashboard/subreddits'
    | '/api/auth/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/_protected/dashboard'
    | '/_protected/new'
    | '/_protected/settings'
    | '/_protected/dashboard/alerts'
    | '/_protected/dashboard/inbounds'
    | '/_protected/dashboard/mentions'
    | '/_protected/dashboard/outbound'
    | '/_protected/dashboard/settings'
    | '/_protected/dashboard/subreddits'
    | '/api/auth/$'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/new': {
      id: '/_protected/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ProtectedNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/alerts': {
      id: '/_protected/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof ProtectedDashboardAlertsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/inbounds': {
      id: '/_protected/dashboard/inbounds'
      path: '/inbounds'
      fullPath: '/dashboard/inbounds'
      preLoaderRoute: typeof ProtectedDashboardInboundsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/mentions': {
      id: '/_protected/dashboard/mentions'
      path: '/mentions'
      fullPath: '/dashboard/mentions'
      preLoaderRoute: typeof ProtectedDashboardMentionsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/outbound': {
      id: '/_protected/dashboard/outbound'
      path: '/outbound'
      fullPath: '/dashboard/outbound'
      preLoaderRoute: typeof ProtectedDashboardOutboundRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/subreddits': {
      id: '/_protected/dashboard/subreddits'
      path: '/subreddits'
      fullPath: '/dashboard/subreddits'
      preLoaderRoute: typeof ProtectedDashboardSubredditsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAlertsRoute: typeof ProtectedDashboardAlertsRoute
  ProtectedDashboardInboundsRoute: typeof ProtectedDashboardInboundsRoute
  ProtectedDashboardMentionsRoute: typeof ProtectedDashboardMentionsRoute
  ProtectedDashboardOutboundRoute: typeof ProtectedDashboardOutboundRoute
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardSubredditsRoute: typeof ProtectedDashboardSubredditsRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAlertsRoute: ProtectedDashboardAlertsRoute,
  ProtectedDashboardInboundsRoute: ProtectedDashboardInboundsRoute,
  ProtectedDashboardMentionsRoute: ProtectedDashboardMentionsRoute,
  ProtectedDashboardOutboundRoute: ProtectedDashboardOutboundRoute,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardSubredditsRoute: ProtectedDashboardSubredditsRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedNewRoute: typeof ProtectedNewRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedNewRoute: ProtectedNewRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
