import type { RedditThread, ProjectSubreddit } from '@repo/database'

export interface DemoProjectContext {
  url: string
  description: string
  targetAudience: string
  keywords: string[]
}

export interface DemoDashboardData extends DemoProjectContext {
  name: string
  threads: RedditThread[]
  subreddits: ProjectSubreddit[]
}

// Static snapshot of the demo workspace shown on the landing page preview.
// No fetching - data is embedded in the web bundle.
export const DEMO_DASHBOARD_DATA: DemoDashboardData = {
  name: 'Screenly',
  url: 'https://screenly-website.vercel.app',
  description:
    'Screenly is an open-source Android app that helps users combat smartphone addiction by locking distracting applications. It leverages financial incentives via USDC deposits on Solana, where users stake money and lose it if they fail to meet their screentime goals.',
  targetAudience:
    'Individuals struggling with smartphone addiction, students and professionals seeking to improve their focus and productivity, and anyone looking for a strong, financially-backed method to reduce screentime and cultivate digital discipline.',
  keywords: ['Screentime management', 'Productivity app', 'Digital detox', 'Solana blockchain', 'Loss aversion'],
  threads: [
    {
      id: "cmsrtpk1v000c5cvf0oeybq5j",
      redditId: "1vlml0g",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "what productivity stuff do you still struggle to do even using planners, reminders, or apps?",
      body: "I noticed I sometimes forget simple things I planned to do (like laptop tasks, or small stuff like saving links or lists) Curious if many people experience this too.\n\neven when I set a reminder, I can still end up forgetting or ignoring it.\n\nHow about you? What productivity problems do you still struggle with even after using reminders, planners, or apps? (if u use any) ",
      author: "DistinctAd4242",
      url: "https://reddit.com/r/productivity/comments/1vlml0g/what_productivity_stuff_do_you_still_struggle_to/",
      score: 2,
      commentCount: 4,
      redditCreatedAt: new Date("2026-08-11T16:37:34.000Z"),
      priority: "medium",
      intentReason: "User struggles with productivity and often forgets or ignores planned tasks, even with reminders and apps. This points to a general challenge with focus and task execution, which excessive digital distraction often exacerbates. - Pitch Strategy: Engage by acknowledging the common struggle with maintaining focus despite planning. Suggest that sometimes the hurdle isn't just remembering tasks, but overcoming the temptation of digital distractions that pull us away. Mention that for specific mobile distractions, leveraging strong commitments like financial incentives (as offered by apps like Screenly) can be a powerful way to enforce focused work periods by actively preventing app access.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:03.523Z"),
    },
    {
      id: "cmsrtpk78000d5cvfamt61113",
      redditId: "1vkowro",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "anyone do shared daily goals with their partner?",
      body: "Me and my partner were talking about this bc I swear I get way more stuff done when I know someone else can actually see whether I did it??\n\nWe both use seperate todo lists rn, but I was thinking it'd be kinda fun if every morning we just put like 3 things we wanna get done and could see each others progress throughout the day.\n\nDoes anyone actually do this with their partner or even a friend? Like is there an app thats good for this already? keeping each other productive typa thing",
      author: "IncreaseUnusual",
      url: "https://reddit.com/r/productivity/comments/1vkowro/anyone_do_shared_daily_goals_with_their_partner/",
      score: 5,
      commentCount: 9,
      redditCreatedAt: new Date("2026-08-10T16:00:34.000Z"),
      priority: "high",
      intentReason: "User is seeking an app for shared daily goals and accountability with a partner to boost productivity, directly addressing the need for external motivation to achieve goals. - Pitch Strategy: Start by discussing the proven effectiveness of social accountability for motivation and goal achievement. Then, introduce the concept that for some, an even stronger personal motivator can be financial stakes or direct personal commitments. Mention that for individual focus and reducing digital distractions that derail goals, some tools (like Screenly for Android) allow users to put money on the line to enforce screen time limits, serving as a powerful, self-imposed accountability mechanism.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:03.716Z"),
    },
    {
      id: "cmsrtpjw3000b5cvfajtxjnxc",
      redditId: "1vbsxw0",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "App/website blocker on laptop that uses a password system",
      body: "Hi all. On my iphone, my screentime is quite well managed, with the weekly average being 2 hours, sometimes 3 (including google maps and music and other benign stuff). I have no problems obeying my blocks via the screentime app, because my girlfriend has the screen time password.\n\nI would like to have a similar system set up on my laptop, but here is my issue. All the more popular apps (freedom, cold turkey, etc.) could have the features I want, but are paid. Is there any FREE app/website blocker that blocks websites and such after a certain time limit is met, with that blocker being unable to be circumvented except via the entering of a password?\n\nBrowser extensions are very easy to circumvent as you can just turn them off, unfortunately. So, I think an actual app you can download is the only thing that could work.",
      author: "ARunningTide",
      url: "https://reddit.com/r/productivity/comments/1vbsxw0/appwebsite_blocker_on_laptop_that_uses_a_password/",
      score: 4,
      commentCount: 1,
      redditCreatedAt: new Date("2026-07-31T14:44:00.000Z"),
      priority: "high",
      intentReason: "User is actively seeking an app/website blocker and a system for external accountability to manage screen time on their laptop, directly aligning with Screenly's core purpose of combating digital distractions. - Pitch Strategy: Validate their current successful strategy (girlfriend holding password) as a strong form of external accountability. Discuss the broader principle of how self-discipline often needs reinforcement and how significant personal stakes (like financial incentives, as leveraged by some apps for digital discipline on mobile) can provide an even more robust enforcement mechanism against distractions, regardless of the specific platform.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:03.316Z"),
    },
    {
      id: "cmsrtpkcx000e5cvfqfaweebp",
      redditId: "1v9tpbj",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "I've slowly made my phone less interesting, and I don't miss it. What else can I do?",
      body: "Over the last few months I've been trying to break my phone addiction\n\nThese are the things I did to accomplish this:\n\n* deleted social media\n* turned off all notifications for apps\n* switched to grayscale\n* picked up physical books again\n* kept my phone charger out of my bedroom.\n\nI've actually found that I didn't miss having social media as much as I was led to believe I would miss it. Now, I'm curious what other small things you've done that made a huge difference in your day to day life.\n\nDon't list productivity tips, only things that had surprisingly positive effects.",
      author: "Accomplished_Fly_951",
      url: "https://reddit.com/r/productivity/comments/1v9tpbj/ive_slowly_made_my_phone_less_interesting_and_i/",
      score: 7,
      commentCount: 1,
      redditCreatedAt: new Date("2026-07-29T11:39:57.000Z"),
      priority: "high",
      intentReason: "User is actively seeking strategies to combat phone addiction and improve focus, a core problem Screenly solves. - Pitch Strategy: Start by sharing general non-product tips (e.g., mindful usage, setting specific phone-free times, creating physical barriers). Once trust is established and if the user expresses continued struggle despite these methods or asks for more 'robust' solutions, mention Screenly as a unique, financially-backed option for serious commitment, highlighting its open-source nature.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:03.922Z"),
    },
    {
      id: "cmsrtpkie000f5cvf5498neyg",
      redditId: "1v7nzm2",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "Why do I find it so hard to do anything?",
      body: "I have so many goals and things I want to accomplish yet I never do any of it. I’ve struggled with productivity my whole adult life. It’s not lack of wanting to do it, it’s like something in my brain literally blocks me and avoids progress at all costs. For example: I’ve been working on an app to launch for a while now, and now that it’s almost complete I can’t bring myself to finish it and actually launch. I’ve also gone through hyper fixation phases since I was a kid where if I want something I obsess over it for a few months then I move on like it doesn’t exist. One example would be I wanted to buy a car with cash, I made a goal to save 20k and once I bought the car I had no desire to keep saving money for my future and never saved anymore. I hate my lack of productivity and drive to accomplish things but also wanting to accomplish so much. I feel like something is wrong with me. I’ve also been suspicious I have adhd (I was a super hyperactive child with behavioral issues. Now I’m a very calm adult that will sit at home doing nothing all night rather than going out and living life yet I strongly desire to go out and do things). I still haven’t done my taxes from LAST year even though it will only take a few minutes since my taxes are pretty straightforward. Am I just extremely lazy? Can anyone relate to any of this? What helped turn things around for you? ",
      author: "UnderstandingNo664",
      url: "https://reddit.com/r/productivity/comments/1v7nzm2/why_do_i_find_it_so_hard_to_do_anything/",
      score: 2,
      commentCount: 2,
      redditCreatedAt: new Date("2026-07-27T02:45:29.000Z"),
      priority: "medium",
      intentReason: "User struggles with general productivity and procrastination, which can often be exacerbated by smartphone distractions. Screenly can address a key blocker. - Pitch Strategy: Offer general productivity advice first (e.g., breaking tasks into smaller steps, accountability partners, time blocking). If the conversation reveals a struggle with focus or getting distracted during deep work, then introduce Screenly as a powerful tool to eliminate phone-based distractions that often derail productivity, especially for those who need a strong commitment mechanism.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:04.118Z"),
    },
    {
      id: "cmsrtpko9000g5cvfjl38rnt8",
      redditId: "1v72ow6",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "What makes a productivity app genuinely useful to you?",
      body: "I mainly use Notion, although I’ve tried a few other productivity apps here and there. It works well for me, but I’m curious about how other people use these kinds of apps and what makes them worth sticking with.\n\nFor people who use Notion, Todoist, TickTick, Trello or something similar, what makes the app genuinely useful in your everyday life? Is there anything you still struggle with that these apps don’t really solve?",
      author: "Haunting_Length1505",
      url: "https://reddit.com/r/productivity/comments/1v72ow6/what_makes_a_productivity_app_genuinely_useful_to/",
      score: 3,
      commentCount: 27,
      redditCreatedAt: new Date("2026-07-26T12:34:59.000Z"),
      priority: "medium",
      intentReason: "User is seeking insights on productivity apps and areas where current solutions fall short. Screenly addresses a common limitation: maintaining focus and avoiding distractions that prevent effective use of other productivity tools. - Pitch Strategy: Engage by discussing how task managers are great, but often the biggest hurdle is the discipline to actually use them and avoid phone distractions that pull you away. Then, introduce Screenly as a complementary tool that tackles the root cause of distraction, enabling users to actually stick to their productivity systems by making it financially painful to deviate from focus goals.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:04.329Z"),
    },
    {
      id: "cmsrtpktu000h5cvf2i62o5vq",
      redditId: "1v50bih",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "How to kick a screen time addiction",
      body: "The main hinderance to my productivity is being on my phone. I’ve tried apps to block social media apps and it still hasn’t worked. The worst is getting started in the morning and in the evening, but I struggle with it all throughout the workday too",
      author: "sfogliniwizard",
      url: "https://reddit.com/r/productivity/comments/1v50bih/how_to_kick_a_screen_time_addiction/",
      score: 19,
      commentCount: 33,
      redditCreatedAt: new Date("2026-07-24T03:58:53.000Z"),
      priority: "high",
      intentReason: "User explicitly describes phone addiction as a primary productivity hinderance and states traditional app blockers haven't worked, making Screenly's financial incentive a direct and compelling solution. - Pitch Strategy: Start by empathizing with the struggle and acknowledging the limitations of standard blocking apps. Then, introduce the concept of leveraging financial incentives for discipline as a more robust solution when willpower alone fails, and naturally present Screenly as an open-source Android app that does exactly this, allowing users to stake money to enforce their screentime goals.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:04.530Z"),
    },
    {
      id: "cmsrtpkz7000i5cvfffqelyfx",
      redditId: "1uz0qo8",
      channel: "reddit",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      subreddit: "r/productivity",
      title: "Real tools that work (not just hype)",
      body: "I read a lot of top 10 list of productivity tools - my fav right now is a mix of del based tools that can generate websites and apps as well as good old fashioned video editing tools but rather than a AI slop top 10 what's one or two tools you actually use that's say on your mobile or desk top - AI platforms welcome but not the silly ones like turn your hand drawn meeting notes notes into songs etc.  ",
      author: "YTdeancousinTV",
      url: "https://reddit.com/r/productivity/comments/1uz0qo8/real_tools_that_work_not_just_hype/",
      score: 1,
      commentCount: 10,
      redditCreatedAt: new Date("2026-07-17T14:05:48.000Z"),
      priority: "high",
      intentReason: "User is explicitly asking for 'real tools that work' for productivity, especially on mobile, which directly aligns with Screenly's offering of a unique, non-hyped approach to digital discipline. - Pitch Strategy: Start by sharing a brief, authentic endorsement of Screenly's effectiveness in combating phone addiction for serious productivity goals, emphasizing its unique financial incentive model as a 'real tool that works' for strong commitment, contrasting it with typical 'hype.' Mention it's an open-source Android app designed for digital discipline.",
      isDone: false,
      generatedReply: null,
      fetchedAt: new Date("2026-08-13T18:00:04.724Z"),
    },
  ],
  subreddits: [
    {
      id: "cmsrtnnoy00035cvfajtxivjm",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      name: "r/productivity",
      relevance: 95,
      description: "Tips and tricks for being more productive!",
      rulesJson: null,
      createdAt: new Date("2026-08-13T17:58:34.930Z"),
      updatedAt: new Date("2026-08-13T17:58:34.930Z"),
    },
    {
      id: "cmsrtno8s00045cvfo2y06o4b",
      projectId: "cmsrtnmwk00025cvfxz9gx547",
      name: "r/getdisciplined",
      relevance: 95,
      description: "**r/GetDisciplined** is a community focused on building real self-discipline. Share practical strategies, personal experiences, and thoughtful advice to help yourself and others make lasting improvements and achieve meaningful goals.",
      rulesJson: null,
      createdAt: new Date("2026-08-13T17:58:35.644Z"),
      updatedAt: new Date("2026-08-13T17:58:35.644Z"),
    },
  ],
}
